# -*- coding: utf-8 -*-
"""Data structures.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DAyMjESRqe-7ytCiOEIQ8jYGGr7sOs5v
"""

# 1.Assigning elements to different lists

#Accesing elements from a list
fruits = ['apple','banana','orange']
fruits.append('cherries')
fruits.insert(1,'apricots')
fruits.extend(['straw berry','pineapple','limes'])
print(fruits,'\n')

#Assigning elements of list1 to list2
list1 = ['iron','man']
list2 = ['i','am']
print("ORIGINAL LIST1:",list1)
print("ORIGINAL LIST2:",list2)
for i in list1:
  list2.append(i)
print('modified list2 :',list2)
list1 = list2.copy()
print('Modified list1:',list1)

# 2.Acessing elements from a tuple

tuple1 = ('we','love','you',3000)
for i in range(4):
     print(tuple1[i],end =' ')
print('\n')

# 3.Deleting different dictionary elements

dict = {1:'Too',2:'Clever',3:'is',4:'Dumb'}
print("Initial dictionary:")
print(dict)
del dict[1]
print("Dictionary after deleting:")
print(dict)
x = dict.pop(3)
print("Dictionary after deleting:")
print(dict)
print('Value associated to poped key is:',x)
dict.clear()
print("Deleting entire dictionary:")
print(dict)